/*
  check-visual.mjs — the only gate in this repo that compares PIXELS.

  Every other check we own compares NUMBERS: token values, geometry read back out
  of getComputedStyle, text nodes, photo order. All of them can be green while the
  page looks wrong, because they only assert about properties somebody thought to
  assert about. This one renders our build and the reference at the same size and
  subtracts them, so it catches the class of defect the others cannot see by
  construction — something in the wrong PLACE, or something the reference draws
  that we do not draw at all.

  EXIT CODES (same convention as check-copy-verbatim.mjs):
    0  ran, and every view is within budget
    1  ran, and found differences over budget — real findings
    2  PRECONDITION FAILED — could not run. Never silently green.

  The 2 matters more than it looks. A previous gate in this repo skipped green when
  it could not reach a server, so `npm run verify` asserted nothing about copy for
  weeks while reporting a pass. A check that cannot run must say so loudly and fail
  the build; "no findings" and "no comparison" are not the same sentence.

  BASELINES ARE NOT COMMITTED and cannot be regenerated by this script. They are
  screenshots of the live reference, which sits behind Vercel Attack Challenge Mode
  + BotID and 429s any Playwright-LAUNCHED browser — capture needs connectOverCDP
  against a browser a human opened. `_reference/tools/shot-reference.mjs` does that
  half. If the PNGs are absent this exits 2 and says which one and how to make it,
  rather than inventing a baseline.

  Usage:
    node scripts/check-visual.mjs                 # build if needed, start, diff all views
    node scripts/check-visual.mjs --base=http://localhost:3000   # diff against a running server
    node scripts/check-visual.mjs --views=listing,photo-tour
*/
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import { chromium } from "./playwright.mjs";
import { compare, decode, tally, writeDiffImage, gridRegions, THRESHOLD } from "./visual-diff.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const BASELINE = join(ROOT, "_reference", "baseline");
const OUT = join(ROOT, "_reference", "visual-diff");

const WIDTH = 1910;
const HEIGHT = 1000;

// Reserved for this worker. A shared port and a shared .next are how two of this
// repo's checks previously reported red on green code.
const PORT = Number(argOf("port") || 3211);
const DIST = ".next-visual";

/*
  BUDGET — the number above which a region is called a finding.

  0.5% of a region's area, in STRUCTURAL pixels (see visual-diff.mjs for the
  three-way classification). Not zero, and deliberately not: two Chromium renders
  of byte-identical CSS do not produce byte-identical pixels, and photographic
  content re-encoded through two different image pipelines differs everywhere at
  the per-pixel level while looking the same to a person.

  0.5% is a working value chosen so that the smallest thing we actually care about
  — a 40x40 control 4px out of place, which is ~160 structural pixels in a
  191x125 grid cell, or 0.67% — clears it. It is a threshold on a judgement, so it
  is stated here rather than buried, and the report prints the raw counts too so
  nobody has to trust it.
*/
const REGION_BUDGET_PCT = 0.5;

function argOf(name) {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : null;
}

function die(code, ...lines) {
  console.error("");
  for (const l of lines) console.error(l);
  process.exit(code);
}

/*
  THE THREE GRADED VIEWS.

  Each is reached by CLICKING the control a user clicks, not by pushing a URL.
  Our overlay URL scheme is modelled on the reference's, but a view captured by
  asserting a URL scheme is a view captured on an assumption; if the assumption is
  wrong the harness diffs the listing against the tour and blames the tour. The
  click path cannot land somewhere else without failing outright.

  `ready` is asserted BEFORE the screenshot in every case. god lost an answer this
  session to a selector that matched a control existing twice — the tour and the
  viewer are both [role="dialog"] and both mounted at once — so every selector
  below is scoped to a named dialog and every view proves it is open first.
*/
/*
  OUR tour dialog is labelled `All photos of <title>`; the reference labels its
  `Photo tour`. Both viewers are labelled `Photo viewer`. The selector below has to
  match OUR side, because that is the only side this script drives — the baseline
  was captured by shot-reference.mjs against the reference's own labels.

  (The label mismatch is not itself a visual difference — nothing renders it — so it
  is not this harness's finding to file. Noted here only so the next person does not
  "fix" this selector to match the reference and quietly break every tour capture.)
*/
const OUR_TOUR = '[role="dialog"][aria-label^="All photos of"]';
const OUR_VIEWER = '[role="dialog"][aria-label="Photo viewer"]';

const VIEWS = {
  listing: {
    async drive(page) {
      await page.evaluate(() => window.scrollTo(0, 0));
      await page.waitForTimeout(400);
    },
    async assertOpen(page) {
      const h1 = await page.locator("h1").first().innerText();
      if (!h1?.trim()) throw new Error("no h1 text — the listing did not render");
      return h1.trim().slice(0, 50);
    },
  },
  "photo-tour": {
    async drive(page) {
      await page.locator('[data-testid="show-all-photos"]').first().click({ timeout: 15000 });
      await page.waitForTimeout(1200);
    },
    async assertOpen(page) {
      const d = page.locator(OUR_TOUR);
      await d.waitFor({ state: "visible", timeout: 15000 });
      return `tour open, ${await d.locator("img").count()} imgs`;
    },
  },
  lightbox: {
    async drive(page) {
      await page.locator('[data-testid="show-all-photos"]').first().click({ timeout: 15000 });
      await page.locator(OUR_TOUR).waitFor({ state: "visible", timeout: 15000 });
      // Scoped to the tour AND to the photo buttons — a bare `button img` here hits
      // the 9-thumbnail filmstrip, which scrolls the tour instead of opening the
      // viewer. The run then does not error; it waits for a dialog nobody opened.
      await page
        .locator(OUR_TOUR + ' button[aria-label*="view full screen"]')
        .first()
        .click({ timeout: 15000 });
      await page.waitForTimeout(1200);
    },
    async assertOpen(page) {
      const d = page.locator(OUR_VIEWER);
      await d.waitFor({ state: "visible", timeout: 15000 });
      const t = (await d.innerText()).replace(/\s+/g, " ").trim();
      if (!t) throw new Error("viewer mounted but empty — not a real open");
      return t.slice(0, 50);
    },
  },
};

/*
  NAMED REGIONS, READ OUT OF OUR OWN DOM AT RUNTIME.

  Hardcoding rectangles would mean the report's region names drift from the page
  the moment anyone moves a section. Reading them live means "hero gallery" always
  means the element that is actually the hero gallery.

  The catch, stated because it changes how the output should be read: if OUR
  element is in the wrong place, the named region is in the wrong place too, and
  the difference can fall outside it. That is exactly why the fixed grid below runs
  as well and is reported alongside. The grid has no blind spot; the names are for
  legibility.
*/
const NAMED = {
  listing: [
    ["site header", "header"],
    ["title block", "h1"],
    ["hero gallery", "#photos"],
    ["show all photos button", '[data-testid="show-all-photos"]'],
  ],
  "photo-tour": [
    ["tour header", OUR_TOUR + " header"],
    ["tour close", OUR_TOUR + ' [aria-label="Close photo tour"]'],
    ["tour dialog", OUR_TOUR],
  ],
  lightbox: [
    ["viewer dialog", OUR_VIEWER],
    ["show all photos (top-left)", OUR_VIEWER + ' [aria-label="Show all photos"]'],
    ["close (top-right)", OUR_VIEWER + ' [aria-label="Close"]'],
    ["previous", OUR_VIEWER + ' [aria-label="Previous photo"]'],
    ["next", OUR_VIEWER + ' [aria-label="Next photo"]'],
  ],
};

async function namedRegions(page, view) {
  const specs = NAMED[view] || [];
  const out = [];
  for (const [name, sel] of specs) {
    const box = await page
      .locator(sel)
      .first()
      .boundingBox()
      .catch(() => null);
    if (box && box.width > 0 && box.height > 0) out.push({ name, ...box });
  }
  return out;
}

// --- preconditions ----------------------------------------------------------

const requested = (argOf("views") || Object.keys(VIEWS).join(",")).split(",").map((s) => s.trim());
for (const v of requested) if (!VIEWS[v]) die(2, `PRECONDITION: unknown view "${v}". Known: ${Object.keys(VIEWS).join(", ")}`);

if (!existsSync(BASELINE)) {
  die(
    2,
    "PRECONDITION FAILED: no reference baseline.",
    `  expected: ${BASELINE}`,
    "  Baselines are screenshots of the LIVE reference and cannot be produced here:",
    "  the site 429s any Playwright-launched browser. Capture needs a human-opened",
    "  browser with CDP exposed, then:",
    "      node _reference/tools/shot-reference.mjs <cdp-port>",
    "  NOT RUN — this is not a pass.",
  );
}

const missing = requested.filter((v) => !existsSync(join(BASELINE, `${v}.png`)));
if (missing.length === requested.length) {
  // Still write the report. DELTA-VISUAL.md is the artefact people read, and a
  // stale one from a previous run is worse than an empty one — it would keep
  // asserting findings that nothing has re-measured. The doc must always describe
  // the LAST RUN, including when the last run compared nothing.
  writeReport([], [], []);
  die(
    2,
    `PRECONDITION FAILED: no baseline PNG for any requested view (${missing.join(", ")}).`,
    `  Capture with: node _reference/tools/shot-reference.mjs <cdp-port>`,
    "  NOT RUN — this is not a pass.",
  );
}
const views = requested.filter((v) => !missing.includes(v));

// --- server -----------------------------------------------------------------

let base = argOf("base");
let server = null;

async function reachable(url) {
  try {
    const r = await fetch(url, { signal: AbortSignal.timeout(3000) });
    return r.ok;
  } catch {
    return false;
  }
}

function run(cmd, args, env) {
  return new Promise((res, rej) => {
    const p = spawn(cmd, args, { cwd: ROOT, env: { ...process.env, ...env }, stdio: "inherit", shell: true });
    p.on("exit", (c) => (c === 0 ? res() : rej(new Error(`${cmd} exited ${c}`))));
  });
}

if (!base) {
  // Reserve the port. Occupied means somebody else's server, and diffing against
  // somebody else's build is how a check reports a defect that is not in the code
  // it claims to be checking.
  if (await reachable(`http://127.0.0.1:${PORT}/`)) {
    die(2, `PRECONDITION FAILED: port ${PORT} is already serving something.`, "  Free it or pass --base=<url>. NOT RUN.");
  }

  const buildId = join(ROOT, DIST, "BUILD_ID");
  if (!existsSync(buildId)) {
    console.log(`no ${DIST}/BUILD_ID — building into ${DIST} ...`);
    try {
      await run("npm", ["run", "build"], { NEXT_DIST_DIR: DIST });
    } catch (e) {
      die(2, `PRECONDITION FAILED: build failed (${e.message}). NOT RUN.`);
    }
  }
  if (!existsSync(buildId)) die(2, `PRECONDITION FAILED: build produced no ${DIST}/BUILD_ID. NOT RUN.`);
  console.log(`using build ${readFileSync(buildId, "utf8").trim()}`);

  server = spawn("npm", ["run", "start", "--", "-p", String(PORT)], {
    cwd: ROOT,
    env: { ...process.env, NEXT_DIST_DIR: DIST },
    stdio: "ignore",
    shell: true,
    detached: false,
  });
  base = `http://127.0.0.1:${PORT}`;
  const deadline = Date.now() + 90000;
  while (Date.now() < deadline && !(await reachable(base + "/"))) await new Promise((r) => setTimeout(r, 1000));
  if (!(await reachable(base + "/"))) {
    server.kill();
    die(2, `PRECONDITION FAILED: server on ${PORT} never became reachable. NOT RUN.`);
  }
}
console.log(`comparing ${base} against ${BASELINE}\n`);

// --- capture ours -----------------------------------------------------------

mkdirSync(OUT, { recursive: true });

const browser = await chromium.launch({ headless: true });
// deviceScaleFactor pinned to 1 on purpose. The baseline is DPR 1 (forced through
// Emulation.setDeviceMetricsOverride on the reference side); a DPR 2 capture here
// would be a 3820x2000 image and every comparison would be a size mismatch, or
// worse, a silent downscale that blurs exactly the 1px offsets we are looking for.
const ctx = await browser.newContext({
  viewport: { width: WIDTH, height: HEIGHT },
  deviceScaleFactor: 1,
});
const page = await ctx.newPage();

const report = [];
const failures = [];

for (const view of views) {
  process.stdout.write(`[${view}] `);
  await page.goto(base + "/", { waitUntil: "domcontentloaded", timeout: 45000 });
  await page.waitForTimeout(1200);
  let state;
  try {
    await VIEWS[view].drive(page);
    state = await VIEWS[view].assertOpen(page);
  } catch (e) {
    console.log(`COULD NOT REACH THE VIEW :: ${e.message}`);
    failures.push({ view, precondition: `could not reach the view: ${e.message}` });
    continue;
  }

  // Let images decode. A screenshot mid-stream records grey boxes and reports them
  // as our defect.
  await page
    .waitForFunction(() => [...document.images].every((i) => !i.getAttribute("src") || i.complete), null, { timeout: 20000 })
    .catch(() => {});
  await page.waitForTimeout(1500);

  const oursPath = join(OUT, `ours-${view}.png`);
  await page.screenshot({ path: oursPath, clip: { x: 0, y: 0, width: WIDTH, height: HEIGHT } });

  const named = await namedRegions(page, view);

  const ours = await decode(oursPath);
  const ref = await decode(join(BASELINE, `${view}.png`));
  if (ours.width !== ref.width || ours.height !== ref.height) {
    console.log("SIZE MISMATCH");
    failures.push({
      view,
      precondition: `size mismatch: ours ${ours.width}x${ours.height}, reference ${ref.width}x${ref.height} — the two sides were not captured at the same metrics, so no comparison is meaningful`,
    });
    continue;
  }

  const cmp = compare(ours, ref);
  await writeDiffImage(ours, cmp, join(OUT, `diff-${view}.png`));

  const regions = [...named, ...gridRegions(WIDTH, HEIGHT)]
    .map((r) => ({ ...r, ...tally(cmp, r), named: !r.name.startsWith("grid ") }))
    .sort((a, b) => b.structural - a.structural);

  const pct = (cmp.structural / cmp.total) * 100;
  console.log(
    `${state} :: structural ${cmp.structural} px (${pct.toFixed(2)}%), edge-shift ${cmp.shifted} px`,
  );
  report.push({ view, state, cmp, pct, regions });
}

await browser.close();
if (server) server.kill();
// The child was spawned with shell:true, so kill() reaps the shell and can leave
// the node server behind holding the port. Clear it explicitly on Windows.
if (server && process.platform === "win32") {
  spawn("cmd", ["/c", `for /f "tokens=5" %a in ('netstat -ano ^| findstr :${PORT} ^| findstr LISTENING') do taskkill /PID %a /F`], {
    stdio: "ignore",
    shell: true,
  });
}

// --- report -----------------------------------------------------------------

console.log("");
const findings = [];
for (const r of report) {
  const over = r.regions.filter((x) => x.pct >= REGION_BUDGET_PCT && x.structural > 200);
  const namedOver = over.filter((x) => x.named);
  const gridOver = over.filter((x) => !x.named);
  console.log(`=== ${r.view} — ${r.pct.toFixed(2)}% of the viewport differs structurally ===`);
  if (!over.length) {
    console.log("  no region over budget");
  }
  for (const x of [...namedOver, ...gridOver].slice(0, 12)) {
    console.log(
      `  ${x.pct.toFixed(1).padStart(5)}%  ${String(x.structural).padStart(7)} px  ` +
        `[${Math.round(x.x)},${Math.round(x.y)} ${Math.round(x.w)}x${Math.round(x.h)}]  ${x.name}`,
    );
  }
  findings.push({ view: r.view, pct: r.pct, over: [...namedOver, ...gridOver] });
  console.log("");
}

writeReport(findings, failures, report);

if (failures.length) {
  console.error("PRECONDITION FAILURES (these views were NOT compared):");
  for (const f of failures) console.error(`  - ${f.view}: ${f.precondition}`);
  console.error("");
}
if (missing.length) {
  console.error(`NOT COMPARED — no baseline PNG: ${missing.join(", ")}`);
  console.error("  Capture with: node _reference/tools/shot-reference.mjs <cdp-port>\n");
}

const hasFindings = findings.some((f) => f.over.length > 0);
if (failures.length || missing.length) {
  console.error(`EXIT 2 — the run was incomplete. ${views.length}/${requested.length} views compared.`);
  process.exit(2);
}
if (hasFindings) {
  console.error("EXIT 1 — regions over budget. See _reference/visual-diff/diff-*.png and docs/spec/DELTA-VISUAL.md");
  process.exit(1);
}
console.log("EXIT 0 — every compared view is within budget.");
process.exit(0);

function writeReport(findings, failures, report) {
  const doc = join(ROOT, "docs", "spec", "DELTA-VISUAL.md");
  mkdirSync(dirname(doc), { recursive: true });
  const manifest = existsSync(join(BASELINE, "manifest.json"))
    ? JSON.parse(readFileSync(join(BASELINE, "manifest.json"), "utf8"))
    : {};
  const L = [];
  L.push("# DELTA-VISUAL — pixel diff against the reference");
  L.push("");
  L.push("Generated by `npm run check:visual`. Do not hand-edit; re-run it.");
  L.push("");
  L.push("## How to read this");
  L.push("");
  L.push(
    `Two browser renders of identical CSS are never bit-identical, so a raw pixel diff is worthless. Every differing pixel here is classified: **edge-shift** (the same colour exists within one pixel in the other image — anti-aliasing, hinting, sub-pixel text placement) or **structural** (nothing like it nearby — something is in a different place, a different colour, or absent). Ranking is by structural pixels only. Per-pixel tolerance is YIQ distance > ${THRESHOLD}; a region is a finding at >= ${REGION_BUDGET_PCT}% structural of its own area and > 200 px.`,
  );
  L.push("");
  L.push(
    "A large edge-shift count with near-zero structural is itself a result: same shapes, different glyph rasterisation. That is a typography question, not a layout one.",
  );
  L.push("");
  L.push("## Capture conditions");
  L.push("");
  L.push(`- viewport **${WIDTH}x${HEIGHT}, DPR 1** on both sides`);
  L.push(`- baseline captured: ${manifest.capturedAt || "(unknown)"} from ${manifest.ref || "(unknown)"}`);
  L.push(`- reference fonts fetched at capture: ${(manifest.fonts || []).join(", ") || "(none recorded)"}`);
  L.push(`- our build: git ${process.env.VISUAL_SHA || tryGitSha()}`);
  L.push("");
  if (failures.length || missing.length) {
    L.push("## NOT COMPARED");
    L.push("");
    for (const m of missing) L.push(`- **${m}** — no baseline PNG. Capture needs the live reference over CDP.`);
    for (const f of failures) L.push(`- **${f.view}** — ${f.precondition}`);
    L.push("");
  }
  L.push("## Ranked findings");
  L.push("");
  if (!report.length) L.push("_No view was compared._");
  for (const r of report) {
    L.push(`### ${r.view} — ${r.pct.toFixed(2)}% of the viewport differs structurally`);
    L.push("");
    L.push(`Diff image: \`_reference/visual-diff/diff-${r.view}.png\` (red = structural, yellow = edge-shift).`);
    L.push("");
    const over = r.regions.filter((x) => x.pct >= REGION_BUDGET_PCT && x.structural > 200);
    if (!over.length) {
      L.push("No region over budget.");
      L.push("");
      continue;
    }
    L.push("| structural % | structural px | edge-shift px | box (x,y,w,h) | region |");
    L.push("| ---: | ---: | ---: | :--- | :--- |");
    for (const x of over.slice(0, 25)) {
      L.push(
        `| ${x.pct.toFixed(1)} | ${x.structural} | ${x.shifted} | ${Math.round(x.x)},${Math.round(x.y)},${Math.round(x.w)},${Math.round(x.h)} | ${x.named ? `**${x.name}**` : x.name} |`,
      );
    }
    L.push("");
  }
  writeFileSync(doc, L.join("\n") + "\n");
  console.log(`wrote ${doc}`);
}

function tryGitSha() {
  try {
    return readFileSync(join(ROOT, ".git", "HEAD"), "utf8").trim().slice(0, 40);
  } catch {
    return "(unknown)";
  }
}
